version: '3'


services:

  docker-fluentd:
    container_name: docker-fluentd
    tty: true
    privileged: true
    entrypoint: /entrypoint.sh
    build: 
      context: ./fluentd 
      dockerfile: Dockerfile
    volumes:
      - ./fluentd/config/fluent.conf:/fluentd/etc/fluent.conf
      - ./fluentd/output:/fluentd/output
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "5140/tcp"
    command: command
      - "/bin/sleep"
      - "infinity"
    networks:
      fluentd-system: 
        ipv4_address: 10.100.0.2

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"  

  server: 
    container_name: server
    tty: true
    privileged: true
    entrypoint: /scripts/entrypoint.sh
    links:
      - "docker-fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.100.0.2:24224
        tag: server
        fluentd-async: 'true'
    build: 
      context: ./server
      dockerfile: Dockerfile
    command: 
      - "/bin/sleep"
      - "infinity"
    networks:
      br_sr0:
        ipv4_address: 10.5.0.2
        

  router0: 
    container_name: router0
    tty: true
    privileged: true
    entrypoint: /scripts/router0_config.sh
    links:
      - "docker-fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.100.0.2:24224
        tag: router0
        fluentd-async: 'true'
    build: 
      context: ./router
      dockerfile: Dockerfile
    command: 
      - "/bin/sleep"
      - "infinity"
    networks:
      fluentd-system:
        ipv4_address: 10.100.0.1
      br_sr0:
        ipv4_address: 10.5.0.1
      br_r0r1:
        ipv4_address: 10.1.0.2


  router1: 
    container_name: router1
    tty: true
    privileged: true
    entrypoint: /scripts/router1_config.sh
    links:
      - "docker-fluentd"
    environment:
      - R_GATEWAY=10.1.0.2
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.100.0.2:24224
        tag: router1
        fluentd-async: 'true'
    build: 
      context: ./router
      dockerfile: Dockerfile
    command: 
      - "/bin/sleep"
      - "infinity"
    networks:
      br_r0r1:
        ipv4_address: 10.1.0.1
      br_r1r2: 
        ipv4_address: 10.2.0.2
      br_r1r3:
        ipv4_address: 10.3.0.2


  router2: 
    container_name: router2
    tty: true
    privileged: true
    environment:
      - R_GATEWAY=10.2.0.2
    entrypoint: /scripts/router2_config.sh
    links:
      - "docker-fluentd"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.100.0.2:24224
        tag: router2
        fluentd-async: 'true'
    build: 
      context: ./router
      dockerfile: Dockerfile
    command: 
      - "/bin/sleep"
      - "infinity"
    networks:
      br_r1r2:
        ipv4_address: 10.2.0.1
      br_r2pc0: 
        ipv4_address: 10.0.0.1
      br_r2pc1:
        ipv4_address: 10.0.1.1

  router3:
    container_name: router3 
    tty: true
    privileged: true
    entrypoint: /scripts/router3_config.sh
    links:
      - "docker-fluentd"
    environment:
      - R_GATEWAY=10.3.0.2
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.100.0.2:24224
        tag: router3
        fluentd-async: 'true'
    build: 
      context: ./router
      dockerfile: Dockerfile
    command: 
      - "/bin/sleep"
      - "infinity"
    networks:
      br_r1r3:
        ipv4_address: 10.3.0.1
      br_r3pc2: 
        ipv4_address: 10.0.2.1
      br_r3pc3:
        ipv4_address: 10.0.3.1
      
  
  pc0:
    cap_add:
      - NET_ADMIN
    container_name: pc0
    tty: true
    privileged: true
    entrypoint: /scripts/ip_route.sh
    links:
      - "docker-fluentd"
    environment: 
      - R_GATEWAY=10.0.0.1
      - R_POOL=10.0.0.0/8
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.100.0.2:24224
        tag: pc0
        fluentd-async: 'true'
    build: 
      context: ./pc
      dockerfile: Dockerfile
    networks:
      br_r2pc0: 
        ipv4_address: 10.0.0.50
  
  pc1:
    cap_add:
      - NET_ADMIN
    container_name: pc1
    tty: true
    privileged: true
    entrypoint: /scripts/ip_route.sh
    links:
      - "docker-fluentd"
    environment: 
      - R_GATEWAY=10.0.1.1
      - R_POOL=10.0.0.0/8
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.100.0.2:24224
        tag: pc1
        fluentd-async: 'true'
    build: 
      context: ./pc
      dockerfile: Dockerfile
    networks:
      br_r2pc1: 
        ipv4_address: 10.0.1.50

  pc2:
    cap_add:
      - NET_ADMIN
    container_name: pc2
    tty: true
    privileged: true
    entrypoint: /scripts/ip_route.sh
    links:
      - "docker-fluentd"
    environment: 
      - R_GATEWAY=10.0.2.1
      - R_POOL=10.0.0.0/8
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.100.0.2:24224
        tag: pc2
        fluentd-async: 'true'
    build: 
      context: ./pc
      dockerfile: Dockerfile
    networks:
      br_r3pc2: 
        ipv4_address: 10.0.2.50
  
  pc3:
    cap_add:
      - NET_ADMIN
    container_name: pc3
    tty: true
    privileged: true
    entrypoint: /scripts/ip_route.sh
    links:
      - "docker-fluentd"
    environment: 
      - R_GATEWAY=10.0.3.1
      - R_POOL=10.0.0.0/8
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 10.100.0.2:24224
        tag: pc3
        fluentd-async: 'true'
    build: 
      context: ./pc
      dockerfile: Dockerfile
    networks:
      br_r3pc3: 
        ipv4_address: 10.0.3.50
      

networks:
  fluentd-system:
    driver: bridge
    ipam: 
      config: 
        - subnet: "10.100.0.0/24"

  br_sr0:
    internal: false
    driver: bridge
    ipam: 
      config:
        - subnet: "10.5.0.0/29"
          gateway: 10.5.0.6
  
  br_r0r1:
    internal: false
    driver: bridge
    ipam: 
      config:
        - subnet: "10.1.0.0/29"
          gateway: 10.1.0.6

  br_r1r2:
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.2.0.0/29"
          gateway: 10.2.0.6

  br_r1r3:
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.3.0.0/29"
          gateway: 10.3.0.6

  br_r2pc0:
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/24"
          gateway: 10.0.0.254

  
  br_r2pc1:
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.1.0/24"
          gateway: 10.0.1.254

  br_r3pc2:
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.2.0/24"
          gateway: 10.0.2.254

  
  br_r3pc3:
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.3.0/24"
          gateway: 10.0.3.254
