version: '3'


services:


  server: 
    container_name: server
    tty: true
    build: 
      context: ./server
      dockerfile: Dockerfile
    networks:
      br_sr0:
        ipv4_address: 10.5.0.2
        

  router0: 
    container_name: router0
    tty: true
    build: 
      context: ./router
      dockerfile: Dockerfile
    networks:
      br_sr0:
        ipv4_address: 10.5.0.1
      br_r0r1:
        ipv4_address: 10.1.0.2


  router1: 
    container_name: router1
    tty: true
    build: 
      context: ./router
      dockerfile: Dockerfile
    networks:
      br_r0r1:
        ipv4_address: 10.1.0.1
      br_r1r2: 
        ipv4_address: 10.2.0.2
      br_r1r3:
        ipv4_address: 10.3.0.2


  router2: 
    container_name: router2
    tty: true
    build: 
      context: ./router
      dockerfile: Dockerfile
    networks:
      br_r1r2:
        ipv4_address: 10.2.0.1
      br_r2pc0: 
        ipv4_address: 10.0.0.1
      br_r2pc1:
        ipv4_address: 10.0.1.1

  router3:
    container_name: router3 
    tty: true
    build: 
      context: ./router
      dockerfile: Dockerfile
    networks:
      br_r1r3:
        ipv4_address: 10.3.0.1
      br_r3pc2: 
        ipv4_address: 10.0.2.1
      br_r3pc3:
        ipv4_address: 10.0.3.1
      
  
  pc0:
    cap_add:
      - NET_ADMIN
    container_name: pc0
    tty: true
    build: 
      context: ./pc
      dockerfile: Dockerfile
    volumes:
      - ./pc:/scripts
    networks:
      br_r2pc0: 
        ipv4_address: 10.0.0.50
  
  pc1:
    cap_add:
      - NET_ADMIN
    container_name: pc1
    tty: true
    build: 
      context: ./pc
      dockerfile: Dockerfile
    volumes:
      - ./pc:/scripts
    networks:
      br_r2pc1: 
        ipv4_address: 10.0.1.50

  pc2:
    cap_add:
      - NET_ADMIN
    container_name: pc2
    tty: true
    build: 
      context: ./pc
      dockerfile: Dockerfile
    volumes:
      - ./pc:/scripts
    networks:
      br_r3pc2: 
        ipv4_address: 10.0.2.50
  
  pc3:
    cap_add:
      - NET_ADMIN
    container_name: pc3
    tty: true
    build: 
      context: ./pc
      dockerfile: Dockerfile
    volumes:
      - ./pc:/scripts
    networks:
      br_r3pc3: 
        ipv4_address: 10.0.3.50

    

      

networks:
  br_sr0:
    internal: false
    driver: bridge
    ipam: 
      config:
        - subnet: "10.5.0.0/29"
          gateway: 10.5.0.6
  
  br_r0r1:
    internal: false
    driver: bridge
    ipam: 
      config:
        - subnet: "10.1.0.0/29"
          gateway: 10.1.0.6

  br_r1r2:
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.2.0.0/29"
          gateway: 10.2.0.6

  br_r1r3:
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.3.0.0/29"
          gateway: 10.3.0.6

  br_r2pc0:
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.0.0/24"
          gateway: 10.0.0.254

  
  br_r2pc1:
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.1.0/24"
          gateway: 10.0.1.254

  br_r3pc2:
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.2.0/24"
          gateway: 10.0.2.254

  
  br_r3pc3:
    internal: false
    driver: bridge
    ipam:
      config:
        - subnet: "10.0.3.0/24"
          gateway: 10.0.3.254
