apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: mi-replicaset
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: server
  template:
    metadata: 
      labels: 
        app: server
    spec:      
      containers: 
        - name: nginx-container
          image: nginx:alpine