FROM frrouting/frr:latest

USER root
# RUN apt-get update 
# RUN apt-get install net-tools && apt-get install -y iputils-ping && apt-get install -y iproute2 coreutils iptables

# RUN sysctl net.ipv4.ip_forward=1